# Array Indexing

In [1]:
import numpy as np


## Accessing 1Darray

In [4]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[3])
print(arr[-1])

1
4
4


## Accessing 2D Array

In [7]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[1][0])
print(arr1[0][-1])

5
4


## Accessing 3D array


In [9]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr2)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [10]:
print(arr2[1][1][3])

8


In [11]:
print(arr2[-1][0][-1])

4


In [31]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [32]:
new_arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(new_arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


## Accessng 3D Array

In [43]:
new_3d = np.array([[[1,2,3,4],[5,6,7,8]],[[4,3,2,1],[8,7,6,5]]])
print(new_3d[0:2,0:2,1:3])
print(new_3d[0:len(new_3d),0:len(new_3d),0:len(new_3d)])


[[[2 3]
  [6 7]]

 [[3 2]
  [7 6]]]
[[[1 2]
  [5 6]]

 [[4 3]
  [8 7]]]


In [47]:
print(new_3d[0:len(new_3d),0:new_3d.shape[0],0:new_3d.shape[0]])

[[[1 2]
  [5 6]]

 [[4 3]
  [8 7]]]
