In [1]:
import numpy as np


In [22]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)



[1 2 3 4]
1
int64
(4,)


In [21]:
arr2=np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [1 2 3 4]]
2
(2, 4)


In [36]:
arr3=np.array([[[1,2,3,4],[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[1,2,3,4],[5,6,7,8]]])
print(arr3)
print(arr3.shape)

[[[1 2 3 4]
  [1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [1 2 3 4]
  [5 6 7 8]]]
(2, 3, 4)


In [39]:
zero = np.zeros((2,2,4))
zero

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
one = np.ones((2,2,5))
one

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [45]:
char = np.arange(1,10,2)
char

array([1, 3, 5, 7, 9])

In [47]:
lin=np.linspace(2,20,15)
lin

array([ 2.        ,  3.28571429,  4.57142857,  5.85714286,  7.14285714,
        8.42857143,  9.71428571, 11.        , 12.28571429, 13.57142857,
       14.85714286, 16.14285714, 17.42857143, 18.71428571, 20.        ])

In [49]:
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
print(arr3.reshape(3,2,4))

[[[1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [60]:
y=arr3.flatten()
arr3
arr3[0,0,2]=15
y


array([ 1,  2,  3,  4,  1,  2,  3,  4,  5,  6,  7,  8, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30])

In [54]:
x = arr3.ravel()
arr3[1,1,2]=15
x
arr3

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 1,  2,  3,  4],
        [ 1,  2, 15,  4],
        [ 5,  6,  7,  8]]])

In [61]:
print(arr2)


[[1 2 3 4]
 [1 2 3 4]]


In [66]:

# y = arr2.flatten()
# arr2[0,1]=50
# print(y)
# print(arr2)

[1 2 3 4 1 2 3 4]
[[ 1 50  3  4]
 [ 1  2  3  4]]


In [67]:
y = arr2.ravel()
arr2[0,1]=50
print(y)
print(arr2)

[ 1 50  3  4  1  2  3  4]
[[ 1 50  3  4]
 [ 1  2  3  4]]


In [73]:
arr5=np.array([[10,20,30],[40,50,60]])
print(arr5)
print(arr5.T)


[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


In [85]:
print(arr5[1,:])
print(arr5[arr5>30])
print(arr1[[0,2]])

[40 50 60]
[40 50 60]
[1 3]


In [88]:
arr1[arr1 < arr1.mean() + 3*arr1.std()]

array([1, 2, 3, 4])

In [93]:
print(arr1.mean()+3*arr1.std())

5.854101966249685


In [107]:
marks=np.array([50,45,44,49,40])
print(marks.mean())
print(marks.std())
print(np.full((2,3),10))
print(marks.min())
print(marks.max())
print(np.matmul(marks,marks))
print(marks.sum())


45.6
3.6110940170535577
[[10 10 10]
 [10 10 10]]
40
50
10462
228


In [109]:
arr = np.arange(1_000_000)
arr

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [115]:
import random
print(np.random.seed(42)  )            # makes results reproducible - ALWAYS set this in projects
print(np.random.rand(3)  )             # 3 random floats between 0-1
print(np.random.randint(1, 10, size=5))  # 5 random ints between 1-9
print(np.random.choice([1,2,3], size=2))  # randomly pick from a list

None
[0.37454012 0.95071431 0.73199394]
[5 7 3 7 8]
[1 3]
