## iterating 1D array

In [2]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[4,3,2,1],[8,7,6,5]]])

In [4]:
for x in arr:
    print(x)

1
2
3
4
5


In [5]:
for x in arr2:
    print(x)

[1 2 3 4 5]
[6 7 8 9 0]


In [6]:
for x in arr3:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[4 3 2 1]
 [8 7 6 5]]


In [7]:
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
0


In [8]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
4
3
2
1
8
7
6
5


In [9]:
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
6
7
8
4
3
2
1
8
7
6
5


In [10]:
for x in np.nditer(arr3,flags=['buffered'],op_dtypes='S'):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'4')
np.bytes_(b'3')
np.bytes_(b'2')
np.bytes_(b'1')
np.bytes_(b'8')
np.bytes_(b'7')
np.bytes_(b'6')
np.bytes_(b'5')


In [13]:
import numpy as np
for x in np.nditer(arr2,flags=['buffered'],op_dtypes='S'):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'0')


In [15]:
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [16]:
for idx,x in np.ndenumerate(arr2):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 0


In [17]:
for x in arr2:
    print(x)

[1 2 3 4 5]
[6 7 8 9 0]


In [28]:
# d1arrcon=np.concatenate((arr,arr))
d1arrcon=np.stack((arr,arr))
print(d1arrcon)
# d2arrcon = np.concatenate((arr2,arr2),axis=1)
d2arrcon = np.stack((arr2,arr2),axis=1)
print(d2arrcon)  # we can only concatenate same dimensional array.

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[6 7 8 9 0]
  [6 7 8 9 0]]]


In [30]:
d1arrcon=np.concatenate((arr,arr))
print(d1arrcon)
d2arrcon = np.concatenate((arr2,arr2),axis=1)
print(d2arrcon)

[1 2 3 4 5 1 2 3 4 5]
[[1 2 3 4 5 1 2 3 4 5]
 [6 7 8 9 0 6 7 8 9 0]]
