### Creating 2D Array

In [2]:
import numpy as np
np.eye(3) # Creates three 1's diagonal magtrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.diag([3,2,1,0])

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [18]:
np.diag([1,2,3],2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
np.vander(np.linspace(0,3,5),2)

array([[0.  , 1.  ],
       [0.75, 1.  ],
       [1.5 , 1.  ],
       [2.25, 1.  ],
       [3.  , 1.  ]])

In [6]:
np.random.rand(2,2,4) 

array([[[0.65458712, 0.30899724, 0.22520271, 0.97353395],
        [0.24896411, 0.03488095, 0.48164104, 0.2921726 ]],

       [[0.8898508 , 0.44436181, 0.42890293, 0.21093857],
        [0.63966917, 0.24163462, 0.31714593, 0.90535204]]])

In [7]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [8]:
np.indices((3,1,5))

array([[[[0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2]]],


       [[[0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]]])

In [9]:
np.genfromtxt('data.txt',delimiter=',')


array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.],
       [  0.,   1.,   2.,   3.,   4.,   5.,   3.,  42.,  24.,  12.,  33.,
        766.],
       [ 75.,   4.,  55.,   6.,   4.,   3.,   4.,   6.,   0.,  11.,  12.,
          1.]])

In [10]:
np.loadtxt("main.csv", delimiter = ',', skiprows = 1,dtype = object)

array([['January', 'Jan.', '1', '01'],
       ['Feburary', 'Feb.', '2', '02'],
       ['March', 'Mar.', '3', '03'],
       ['April', 'Apr.', '4', '04'],
       ['May', 'May', '5', '05'],
       ['June', 'June', '6', '06'],
       ['July', 'July', '7', '07'],
       ['August', 'Aug.', '8', '08'],
       ['September', 'Sept.', '9', '09'],
       ['October', 'Oct.', '10', '10'],
       ['November', 'Nov.', '11', '11'],
       ['December', 'Dec.', '12', '12']], dtype=object)

In [11]:
import os
print(os.getcwd())

C:\Users\Dell\pythonds\numpy


In [12]:
# skiprows=1 or skip_header=1 skip the top first row
# skip_footer=1 ---> skips last row
