In [3]:
import numpy as np

### Creating Arrays


In [4]:
a = np.array([1,2,3,4,5,6],dtype='int32')
print(a)

[1 2 3 4 5 6]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,4],[4,5,6],[7,8,9]]])
print(c)
print(c[-1:-1:-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 4]
  [4 5 6]
  [7 8 9]]]
[]


In [7]:
d = np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]]])
print(d)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]]


### Get dimension of Arrays


In [8]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
2
3
4


### Shape

In [9]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


(6,)
(2, 3)
(2, 3, 3)
(1, 1, 4, 4)


### Get datatype

In [10]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int32
int64
int64
int64


## To set datatype

In [11]:
arr = np.array([1,2,3,5,6],dtype='int16')
print(arr.dtype)

int16


### Get size


In [12]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(d.itemsize)

4
8
8
8


In [13]:
arr.itemsize

2

## To calculate total size of array

In [14]:
a.size
print(f"Total size is {a.size*a.itemsize}")
print(f"Total size is {b.size*b.itemsize}")
print(f"Total size is {c.size*c.itemsize}")
print(f"Total size is {d.size*d.itemsize}")


Total size is 24
Total size is 48
Total size is 144
Total size is 128


In [15]:
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)
print(d.nbytes)


24
48
144
128


### To access/change elements in array

In [16]:
print(b[1,2])

6


In [17]:
print(c[1,2,2])

9


In [18]:
a[0:]

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [19]:
b[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c[-1:-2:-1]

array([[[1, 2, 4],
        [4, 5, 6],
        [7, 8, 9]]])

### Functions in numpy


In [21]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(0,100,25)

array([ 0, 25, 50, 75])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Operations in numpy


In [27]:
a+a


array([ 2,  4,  6,  8, 10, 12], dtype=int32)

In [28]:
a*a


array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [29]:
a@a

np.int32(91)

In [30]:
b*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
a**a

array([    1,     4,    27,   256,  3125, 46656], dtype=int32)

In [32]:
a-a

array([0, 0, 0, 0, 0, 0], dtype=int32)

### slicing


In [33]:
b[0,:]

array([1, 2, 3])

In [34]:
b[:,2]

array([3, 6])

### Initializingn Different Types of Arrays

In [35]:
# All 0's matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
# ALl 1's
np.ones((2,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [37]:
# any other number
np.full((2,2,2),99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [38]:
np.full_like(a,4)

array([4, 4, 4, 4, 4, 4], dtype=int32)

In [39]:
# With random decimal number
np.random.rand(4,2,3)

array([[[0.43517753, 0.54039102, 0.11217396],
        [0.37777706, 0.77402784, 0.27225298]],

       [[0.09170482, 0.93483137, 0.41846612],
        [0.78819791, 0.28270925, 0.44298245]],

       [[0.78741285, 0.61841378, 0.15110484],
        [0.20068222, 0.62224533, 0.97897533]],

       [[0.72537281, 0.02350149, 0.62418877],
        [0.42089115, 0.20406644, 0.59068392]]])

In [114]:
# RAndom integer numbers
np.random.randint(5,size=(3,5))

array([[1, 3, 3, 2, 3],
       [1, 3, 4, 2, 1],
       [2, 0, 2, 4, 1]], dtype=int32)

In [41]:
# identity matrix
np.identity(5)
# creates identity matrix with 5 rows and 5 columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.random.random_sample(a.shape)

array([0.16195624, 0.25690785, 0.11991116, 0.94537631, 0.67319728,
       0.79687662])

In [43]:
np.random.random_sample(b.shape)

array([[0.2227992 , 0.13433562, 0.63737269],
       [0.68815418, 0.4240349 , 0.95426006]])

In [44]:
print(b.shape)

(2, 3)


In [45]:
arr1 = np.array([1,2,3])
r1 = np.repeat(arr1,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [115]:
#Repeating an array
arr2 = np.array([[1,2,3]])
print(arr2.shape)
r2 = np.repeat(arr2,3,axis=0)
print(r2)

(1, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
arr3 = np.ones((5,5))
arr3[1,1:4]=0
arr3[2,1]=0
arr3[2,3]=0
arr3[2,2]=9
arr3[3,1:4]=0
print(arr3)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
z = np.zeros((3,3))
z[1,1]=9
# print(z)

output[1:4,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
arr3 = np.array([[1, 2, 3],
                [4, 5, 6]])
newarr = np.repeat(arr3,2,axis=0)
print(newarr)
newarr1 = np.repeat(arr3,2,axis=1)
print(newarr1)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


#### Copying arrays

In [120]:
import numpy as np
a = np.array([1,2,3])
b=a
print("a:",a)
print("b:",b)
b[0] = 4
print("After copying")
print("b:",b)
print("a:",a)
# IN this while changing b it also changes a because they are referencing to same location so we should use copy method.

a: [1 2 3]
b: [1 2 3]
After copying
b: [4 2 3]
a: [4 2 3]


In [122]:
c=b.copy()
print(c)
c[0]=10
print("a:",a,"c:",c)

[4 2 3]
a: [4 2 3] c: [10  2  3]


### Mathematics operations

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a-2

array([-1,  0,  1,  2])

In [55]:
a*2

array([2, 4, 6, 8])

In [56]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [57]:
a+=2
a

array([3, 4, 5, 6])

In [58]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [59]:
a**2

array([ 9, 16, 25, 36])

In [60]:
# TAke the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [61]:
np.sin(b)

array([0.84147098, 0.        , 0.84147098, 0.        ])

In [62]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

#### Linear algebra

In [63]:
a=np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [64]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [65]:
c = np.identity(3)
c


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
# Find determinant
np.linalg.det(c)

np.float64(1.0)

### statistics


In [67]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

np.int64(1)

In [69]:
np.max(stats)

np.int64(6)

In [70]:
np.average(stats)

np.float64(3.5)

In [71]:
np.max(stats,axis=1)

array([3, 6])

In [72]:
np.max(stats,axis=0)

array([4, 5, 6])

In [73]:
np.min(stats,axis=1)

array([1, 4])

In [74]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [75]:
np.sum(stats,axis=1)

array([ 6, 15])

In [76]:
np.sum(stats)

np.int64(21)

### Reorganizing array

In [77]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [78]:
after = before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
# Vertically stacking vectors

In [80]:
import numpy as np
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
# Horizontalstack
h1 = np.ones((2,4))
print(h1)
h2= np.zeros((2,2))
print(h2)
print(np.hstack([h1,h2,h1,h2]))
np.hstack([h1,h2])


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

## Load data from file

In [82]:
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.]
 [  0.   1.   2.   3.   4.   5.   3.  42.  24.  12.  33. 766.]
 [ 75.   4.  55.   6.   4.   3.   4.   6.   0.  11.  12.   1.]]


In [83]:
filedata=filedata.astype('int32')
print(filedata)


[[  1  13  21  11 196  75   4   3  34   6   7   8]
 [  0   1   2   3   4   5   3  42  24  12  33 766]
 [ 75   4  55   6   4   3   4   6   0  11  12   1]]


#### Advanced Indexing and Boolean Masking

In [84]:
filedata>=50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True],
       [ True, False,  True, False, False, False, False, False, False,
        False, False, False]])

In [85]:
filedata[filedata>50]

array([196,  75, 766,  75,  55], dtype=int32)

In [86]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [87]:
# returns TRUE if any element in a column is > 50 else FAlSE
np.any(filedata>50,axis=0)

array([ True, False,  True, False,  True,  True, False, False, False,
       False, False,  True])

In [88]:
# returns TRUE if all element in a column is > 50 else FAlSE
np.all(filedata>50,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [89]:
np.all(filedata>50,axis=1)


array([False, False, False])

In [90]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [91]:
np.any(filedata > 50,axis=0)

array([ True, False,  True, False,  True,  True, False, False, False,
       False, False,  True])

In [92]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False,  True, False, False, False, False, False, False,
        False, False, False]])

In [93]:
a=np.array([[2,4,6],[1,3,5]])
b=np.array([[0,2,4],[6,8,10]])


In [94]:
np.sort(a)

array([[2, 4, 6],
       [1, 3, 5]])

In [95]:
arr_new = np.array([3,2,5,1,7,4])
np.argsort(arr_new)  #sorts and gives sorted index as output

array([3, 1, 0, 5, 2, 4])

In [96]:
np.concatenate((a,b),axis=1)

array([[ 2,  4,  6,  0,  2,  4],
       [ 1,  3,  5,  6,  8, 10]])

In [97]:
np.concatenate((a,b),axis=0)

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [98]:
a=np.array([1,2,3,4,3,2,1,4,5,32,56,75,89])
print(np.unique(a,return_index=True))  #helps to remove duplicates

(array([ 1,  2,  3,  4,  5, 32, 56, 75, 89]), array([ 0,  1,  2,  3,  8,  9, 10, 11, 12]))


In [99]:
print(np.unique(a,return_counts=True))

(array([ 1,  2,  3,  4,  5, 32, 56, 75, 89]), array([2, 2, 2, 2, 1, 1, 1, 1, 1]))


In [100]:
b.transpose()

array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

In [101]:
b.view()



array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [102]:
np.split(b,2)

[array([[0, 2, 4]]), array([[ 6,  8, 10]])]

### Flatten

In [103]:
# We can use flatten and ravel methods to flatten our array

In [104]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
a1 = x.flatten()
a1[0]=50
print(a1) #Only changes its new array not the original array
print(x)


[50  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [106]:
a2 = x.ravel()
a2[0]=50  # Change is made to the original array too.
print(a2)
print(x)

[50  2  3  4  5  6  7  8  9 10 11 12]
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
y = np.array([1,2,3,4,5,6])
np.save("np1",y)

In [108]:
z = np.load('np1.npy')
print(z)

[1 2 3 4 5 6]


In [109]:
csv_arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.savetxt('np2.csv',csv_arr)
csv_1 = np.loadtxt('np2.csv')
print(csv_1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [110]:
m = np.array([[1, 2, 3], [4, 5, 6]])

m.sum()          # 21 - sum of everything
print(m.sum(axis=0) )   # [5, 7, 9]  - sum DOWN each column
print(m.sum(axis=1))    # [6, 15]    - sum ACROSS each row

[5 7 9]
[ 6 15]
