## Copy

In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
# copy doesnt change the original array
newarr = arr.copy()
print(arr)
print(newarr)

[1 2 3 4 5]
[1 2 3 4 5]


## View

In [8]:
# view changes the original array too.
arr1 = arr.view()
print(arr1)
arr1[1]=10
print(arr)
print(arr1)

[1 2 3 4 5]
[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [9]:
arr2 = arr1.view()
print(arr2)

[ 1 10  3  4  5]


## SHAPE

In [10]:
# It represents the no of elements present in the array using tuple.
print(arr.shape)

(5,)


In [11]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[4,3,2,1],[8,7,6,5]]])

In [12]:
print(arr2.shape)
print(arr3.shape)

(2, 5)
(2, 2, 4)


## RESHAPE

In [13]:
# It changes the shape of the array.
newarr3 = arr2 .reshape(10,)
print(arr2)
print(arr2.shape)



[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [14]:
arr5 = np.array([1,2,3,4,5,6,7,8,9])
print(arr5.reshape(1,3,3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Flattening array

In [15]:
# Converts any multidimensional array into 1D array
# It can be done using arr.reshape(-1)

In [16]:
arr5.reshape(-1)
print(arr5)

[1 2 3 4 5 6 7 8 9]


In [17]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[4,3,2,1],[8,7,6,5]]])
print(arr3.flatten())
print(arr3.ravel())
print(arr3)
print(np.rot90(arr2))
print(np.flip(arr2,axis=0)) # [[6,7,8,9,0][1,2,3,4,5]]
print(np.flip(arr2,axis=1)) # [[5,4,3,2,1][0,9,8,7,6]]
print(np.fliplr(arr2))
print(np.flipud(arr2))

[1 2 3 4 5 6 7 8 4 3 2 1 8 7 6 5]
[1 2 3 4 5 6 7 8 4 3 2 1 8 7 6 5]
[[[1 2 3 4]
  [5 6 7 8]]

 [[4 3 2 1]
  [8 7 6 5]]]
[[5 0]
 [4 9]
 [3 8]
 [2 7]
 [1 6]]
[[6 7 8 9 0]
 [1 2 3 4 5]]
[[5 4 3 2 1]
 [0 9 8 7 6]]
[[5 4 3 2 1]
 [0 9 8 7 6]]
[[6 7 8 9 0]
 [1 2 3 4 5]]


## Joining arrays

In [18]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.dstack((arr,arr)))

[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]]


In [19]:
print(np.vstack((arr,arr)))

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [21]:
print(np.hstack((arr,arr)))


[1 2 3 4 5 1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [22]:
print(np.stack((arr,arr)))

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [23]:
print(np.concatenate((arr,arr)))

[1 2 3 4 5 1 2 3 4 5]


## Splitting Arrays

In [27]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
newarr = np.array_split(arr2,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
