In [20]:
import numpy as np


In [14]:
std_marks = np.genfromtxt('students.txt',delimiter=',',skip_header=1)
print(std_marks)

[[ 1. 60. 55. 55. 70.]
 [ 2. 57. 56. 59. 60.]
 [ 3. 70. 60. 49. 53.]]


In [4]:
# Displaying marks of student with id 1,2,3
print(f'Marks of student with id {std_marks[0,0].astype(int)} is {std_marks[0,1:]}')
print(f'Marks of student with id {std_marks[1,0].astype(int)} is {std_marks[1,1:]}')
print(f'Marks of student with id {std_marks[2,0].astype(int)} is {std_marks[0,1:]}')

Marks of student with id 1 is [60. 55. 55. 70.]
Marks of student with id 2 is [57. 56. 59. 60.]
Marks of student with id 3 is [60. 55. 55. 70.]


In [11]:
#Print the total marks obtained by each student in all subjects (out of 225)
total_marks = np.sum(std_marks,axis=1)
print(f'Total marks of student with id [{std_marks[0,0].astype(int)},{std_marks[1,0].astype(int)},{std_marks[2,0].astype(int)}] is {total_marks[:]} ')

[241. 234. 235.]
Total marks of student with id [1,2,3] is [241. 234. 235.] 


In [34]:
#Print the highest marks scored by each student along with subject name
print(f'Highest marks of student with id [{std_marks[0,0].astype(int)},{std_marks[1,0].astype(int)},{std_marks[2,0].astype(int)}] is {np.max(std_marks,axis=1)}')

Highest marks of student with id [1,2,3] is [70. 60. 70.]


In [32]:
#Print the highest marks scored by student in each subject
print(f'Highest marks on each subject is  {np.max(std_marks,axis=0)}')

Highest marks on each subject is  [ 3. 70. 60. 59. 70.]


In [7]:
std_marks1 = std_marks[:,1:]
print(std_marks1)


[[60. 55. 55. 70.]
 [57. 56. 59. 60.]
 [70. 60. 49. 53.]]


In [8]:
#Average marks of students in each subject is 
print(np.average(std_marks1,axis=0).round(1))


[62.3 57.  54.3 61. ]


In [9]:
std_marks2=np.genfromtxt('students.txt',delimiter=',',skip_header=1,usecols=(1,2,3,4))
std_marks2

array([[60., 55., 55., 70.],
       [57., 56., 59., 60.],
       [70., 60., 49., 53.]])